/* This file contains stub implementations of the AUTOSAR RTE functions.
   The stub implementations can be used for testing the generated code in
   Simulink, for example, in SIL/PIL simulations of the component under
   test. Note that this file should be replaced with an appropriate RTE
   file when deploying the generated code outside of Simulink.

   This file is generated for:
   Atomic software component:  "ADLK"
   ARXML schema: "4.3"
   File generated on: "26-Oct-2023 09:31:46"  */

#ifndef Rte_ADLK_h
#define Rte_ADLK_h
#include "Rte_Type.h"
#include "Compiler.h"

/* Data access functions */
#define Rte_Write_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg Rte_Write_ADLK_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg(void);

#define Rte_Write_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg Rte_Write_ADLK_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg(void);

#define Rte_Write_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig
  (void);

#define Rte_Read_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg Rte_Read_ADLK_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg Rte_Read_ADLK_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbOUT_DLK_FRLock_flg_VbOUT_DLK_FRLock_flg Rte_Read_ADLK_VbOUT_DLK_FRLock_flg_VbOUT_DLK_FRLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FRLock_flg_VbOUT_DLK_FRLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_FRUnlock_flg_VbOUT_DLK_FRUnlock_flg Rte_Read_ADLK_VbOUT_DLK_FRUnlock_flg_VbOUT_DLK_FRUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FRUnlock_flg_VbOUT_DLK_FRUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RRLock_flg_VbOUT_DLK_RRLock_flg Rte_Read_ADLK_VbOUT_DLK_RRLock_flg_VbOUT_DLK_RRLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RRLock_flg_VbOUT_DLK_RRLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RRUnlock_flg_VbOUT_DLK_RRUnlock_flg Rte_Read_ADLK_VbOUT_DLK_RRUnlock_flg_VbOUT_DLK_RRUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RRUnlock_flg_VbOUT_DLK_RRUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_FRDoorFullOpen_flg_VbOUT_HWA_FRDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_FRDoorFullOpen_flg_VbOUT_HWA_FRDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_FRDoorFullOpen_flg_VbOUT_HWA_FRDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_RRDoorFullOpen_flg_VbOUT_HWA_RRDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_RRDoorFullOpen_flg_VbOUT_HWA_RRDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_RRDoorFullOpen_flg_VbOUT_HWA_RRDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg
  (Boolean* u);

#define Rte_Read_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg
  (Boolean* u);

#define Rte_Write_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FRUnlock_flg_VbOUT_ADLK_FRUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg Rte_Write_ADLK_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FRLock_flg_VbOUT_ADLK_FRLock_flg(void);

#define Rte_Write_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RRUnlock_flg_VbOUT_ADLK_RRUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg Rte_Write_ADLK_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RRLock_flg_VbOUT_ADLK_RRLock_flg(void);

#define Rte_Write_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg Rte_Write_ADLK_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_FRDoorMotorA_flg_VbOUT_ADLK_FRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg Rte_Write_ADLK_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_FRDoorMotorB_flg_VbOUT_ADLK_FRDoorMotorB_flg(void);

#define Rte_Write_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg Rte_Write_ADLK_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_RRDoorMotorA_flg_VbOUT_ADLK_RRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg Rte_Write_ADLK_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_RRDoorMotorB_flg_VbOUT_ADLK_RRDoorMotorB_flg(void);

#define Rte_Write_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FRReleaseLatchStatus_sig_VeOUT_ADLK_FRReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RRReleaseLatchStatus_sig_VeOUT_ADLK_RRReleaseLatchStatus_sig
  (void);

/* Entry point functions */
extern FUNC(void, ADLK_CODE) ADLK_Init(void);
extern FUNC(void, ADLK_CODE) ADLK_Step(void);

#endif
